In [1]:
# imports
import pandas as pd
import numpy as np
import seaborn as sns


In [2]:
# sample code to read in pivot table 
# yay stackoverflow!
# https://stackoverflow.com/questions/55359807/save-pandas-pivot-table-to-include-index-and-columns-names

utility_matrix = pd.read_csv('../../data/user_rating_matrix.csv', index_col=0)
utility_matrix.columns.name = utility_matrix.index.name
utility_matrix.index.name = 'title'
utility_matrix.head()

userId                                     1    2    3    4    5    6    7  \
title                                                                        
'71 (2014)                               0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Round Midnight (1986)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Salem's Lot (2004)                      0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Til There Was You (1997)                0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                                     8    9   10  ...  601  602  603  \
title                                                   ...                  
'71 (2014)                               0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Round Midnight (1986)                   0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Salem's Lot (2004)                      0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Til There Was You (1997)                0.0  0.0  0.0  ...  0.0  0.0  0.0   

userId                                   604  605  606  607  608  609  610  
title                                                                       
'71 (2014)                               0.0  0.0  0.0  0.0  0.0  0.0  4.0  
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Round Midnight (1986)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Salem's Lot (2004)                      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Til There Was You (1997)                0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 610 columns]

In [3]:
from sklearn.neighbors import NearestNeighbors

# knn = NearestNeighbors(algorithm='brute', metric='cosine')
knn = NearestNeighbors()
knn.fit(utility_matrix.values)

print(utility_matrix.values)
# feature_test = to_test['50_samples'].values

[[0.  0.  0.  ... 0.  0.  4. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 ...
 [0.  0.  0.  ... 0.  0.  1.5]
 [4.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]]


In [4]:
# random_movie = np.random.choice(utility_matrix.shape[0])
random_movie = 4442

# Forrest Gump: 3158
# Iron Man: 4442
# Avatar: 688
# 
print("Movie is: ", utility_matrix.index[random_movie])

# print(utility_matrix.shape)


Movie is:  Iron Man (2008)


In [5]:
feature_input = utility_matrix.iloc[random_movie: random_movie+2,:].values.reshape(2,-1) # + 2 for iron man 1 and 2
print(feature_input.shape)
# print(feature_input)

# distances, indices = knn.kneighbors(utility_matrix.iloc[random_movie].values.reshape(1,-1), n_neighbors = 11)
distances, indices = knn.kneighbors(feature_input, n_neighbors = 11)

print(indices)
print(distances)


(2, 610)
[[4442 4443  690 8701 4444 9289 9619 4844 7985 6642 3667]
 [4443 4444 9619  691  544 5408 1552 8703 1553 3727 8701]]
[[ 0.         29.09896905 29.70269348 30.68387199 31.30095845 31.52776554
  31.61091584 31.69779172 31.92569498 32.01562119 32.08192638]
 [ 0.         18.61451047 19.42935923 20.08730943 20.40220576 20.42669822
  20.5121915  20.68211788 20.78460969 20.98809186 21.00595154]]


In [6]:
m=pd.Series(indices[0], name='movie')
d=pd.Series(distances[0], name='distance')

recommendations = pd.concat([m,d], axis=1).sort_values(by='distance', ascending=True)

print(recommendations)
print(utility_matrix.index[random_movie], '...makes sense that it is the closest movie since it is the one we used for query')


    movie   distance
0    4442   0.000000
1    4443  29.098969
2     690  29.702693
3    8701  30.683872
4    4444  31.300958
5    9289  31.527766
6    9619  31.610916
7    4844  31.697792
8    7985  31.925695
9    6642  32.015621
10   3667  32.081926
Iron Man (2008) ...makes sense that it is the closest movie since it is the one we used for query


In [7]:
# def formatted_movie(movie_index): # incoroprate specific genres later...


In [8]:
recommendations.head()

for index, row in recommendations.iterrows():
    if not index: 
        print('initial movie:', utility_matrix.index[row['movie']], '\n')
        continue
    print(index, utility_matrix.index[row['movie']])

initial movie: Iron Man (2008) 

1 Iron Man 2 (2010)
2 Avengers, The (2012)
3 Thor (2011)
4 Iron Man 3 (2013)
5 Watchmen (2009)
6 X-Men: First Class (2011)
7 Kung Fu Panda (2008)
8 Star Trek (2009)
9 Pirates of the Caribbean: At World's End (2007)
10 Guardians of the Galaxy (2014)
